### PR TITLE
Add `StripBuilder::sense` & `TableBuilder::sense`

### PR DESCRIPTION
**Pull request by aleokdev**
Closes <https://github.com/emilk/egui/issues/1553>.

### CODE REVIEW

**Comment by emilk** [comment]
Adding a sense is good, but I think we should add a hover effect to it as well. Everything clickable in egui changes appearance when you hover it. This is what let's you know you can click it. You can follow this pattern:

``` rust
if sense.click || sense.drag {
    let visuals = ui.style().interact(&response);
    ui.painter().rect(
        rect.expand(visuals.expansion),
        visuals.rounding,
        visuals.bg_fill,
        visuals.bg_stroke,
    );
}
```

**Comment by aleokdev** [comment]
Not too sure about how to do that. :sweat_smile: I've tried to put that in `StripLayout::add` after the rect allocation, using the allocated rect as the rect to use in the painter, but I just get entire rectangles:
Screenshot_20220504_122107

I'm not too sure how strips work internally either. Will need to dive into this a bit further.

**Comment by emilk** [comment]
Perhaps don't draw the `fill` part, and only the stroke part. Ideally it should be drawn behind the row, but that's harder because https://github.com/emilk/egui/issues/1516 isn't done yet

**Comment by emilk** [comment]
* Feature implemented in https://github.com/emilk/egui/pull/3347

**Pull request closed without merging**
