### PR TITLE
feat(combobox): implement text wrap for selected text

### PR DESCRIPTION
**Pull request by RobWalt**
- [x] Keep your PR:s small and focused.
- [x] If applicable, add a screenshot or gif.
- [x] Unless this is a trivial change, add a line to the relevant `CHANGELOG.md` under "Unreleased".
- [x] ~~If it is a non-trivial addition, consider adding a demo for it to `egui_demo_lib`.~~
- [x] Remember to run `cargo fmt` and `cargo clippy`.
- [x] Open the PR as a draft until you have self-reviewed it and run `./sh/check.sh`.
- [x] When you have addressed a PR comment, mark it as resolved.

Closes <https://github.com/emilk/egui/issues/2271>.

### CODE REVIEW

**Comment by RobWalt** [comment]
Here are some screenshots showcasing the feature:

1. `wrap_width = 20.0`
image

2. `wrap_width = 40.0`
image

**Comment by RobWalt** [comment]
Here is a better example of why this feature would be important

egui

**Comment by RobWalt** [comment]
egui

I reiterated on the feature and now `wrap` is a method accepting a boolean argument. If it is turned on the selected text will take the maximum available space while still respecting the spacing and icon that come after it.

**Review by emilk — APPROVED** [review]
Thanks!

**Comment by emilk** [comment]
This needs to merge in the main branch before we can merge the PR

**Pull request merged**
