### PR TITLE
Freeze scroll area

### PR DESCRIPTION
**Pull request by edko99**
Closes <https://github.com/emilk/egui/issues/466>.

### CODE REVIEW

**Comment by parasyte** [comment]
This uses the wrong style for the scroll bar when scrolling is disabled. IMHO it looks better with:

```rust
let visuals = ui.style().visuals.widgets.inactive;
```

**Comment by edko99** [comment]
Hi @parasyte, thank you. This is my first contribution ever to open source. Is there anything I need to do to incorporate your changes to the PR?

**Review by emilk — APPROVED** [review]
Code looks good! I haven't tested it, but I assume you have :)

**Comment by edko99** [comment]
@emilk I did :-) thank you!

**Pull request merged**
