### PR TITLE
Make `on_disabled_hover_ui` respect `tooltip_delay`

### PR DESCRIPTION
**Pull request by YgorSouza**
* Closes <https://github.com/emilk/egui/issues/3997>

### CODE REVIEW

**Comment by rustbasic** [comment]
great.

Future Request:
It would be nice to be able to set the delay time.
If you set it to 0.0, it will have a disable effect.

**Comment by YgorSouza** [comment]
@rustbasic it is already possible to set the delay. Introduced in #3245. If you mean you want to use this value to disable the tooltip altogether, I was thinking you could do that by setting it to infinity, but actually this makes the app panic due to a conversion to `Duration`, so I may as well fix that in this branch.

**Comment by rustbasic** [comment]
I see.
I will look forward to the future.

With the following structure, it seems possible to set delay and duration times as well:

(example)
tooltip_delay
tooltip_duration
tooltip_state
tooltip_start_time
tooltip_end_time

1. Create these five variables to set the delay and duration times.
2. When hovering over the widget to display the tooltip, use the current time along with tooltip_delay and tooltip_duration to input tooltip_start_time and tooltip_end_time.
3. If the current time is between tooltip_show_time and tooltip_hide_time, and the widget is in hover state, display the tooltip and set tooltip_state to true.
4. If the current time is not between tooltip_start_time and tooltip_end_time, modify tooltip_state from true to false, and do not display the tooltip.

Have a good day.

**Review by emilk — APPROVED** [review]
Great; thanks you!

**Comment by abey79** [comment]
Thanks @YgorSouza!

**Pull request merged**
