### PR TITLE
Fix crash on Android

### PR DESCRIPTION
**Pull request by emilk**
* Closes https://github.com/emilk/egui/issues/3674

Please try it @rednaz1337 @m-hugo

### CODE REVIEW

**Comment by m-hugo** [comment]
exactly the same .cargo/git/checkouts/egui-5e4507fa4153be06/a474724/crates/eframe/src/native/wgpu_integration.rs:399:69: called `Option::unwrap()` on a `None` value

**Comment by m-hugo** [comment]
if you want to add some logging, just do some `println!`'s

**Comment by emilk** [comment]
Oh right, the main viewport is removed…

I don't own an android device, so it would be better if someone else worked on this.

**Comment by emilk** [comment]
Converting to Draft - If somebody is interested in fixing Android, just fork this and make a new PR

**Pull request closed without merging**
