### PR TITLE
Impls From<Pos2> for Vec2, From<Vec2> for Pos2

### PR DESCRIPTION
**Pull request by fundon**
Impls `From<Pos2>` for `Vec2`, `From<Vec2>` for `Pos2`.

### CODE REVIEW

**Comment by emilk** [comment]
There are a lot of interfaces that take `impl Into<Vec2>` as argument. With this PR, it would be very easy to accidentally pass a position in these places.

**Comment by fundon** [comment]
https://github.com/search?q=repo%3Aemilk%2Fegui%20Into%3CPos2%3E&type=code

Before I was trying to modify the windows position, `default_pos` and `current_pos` accept the `Into<Pos2>` parameter, which would be more convenient if `Vec2` implemented From trait.

**Comment by emilk** [comment]
@fundon why would it be more convenient?  You can use `pos2(x,y)` or `[x,y]` and it will work fine.

**Comment by fundon** [comment]
Ok, we can add it if needed in the future. :)

**Pull request closed without merging**
