### PR TITLE
Response Sense Recognition Issue

### LINKED ISSUE #3989: `Response::interact` doesn't always work
The Sense recognition function does not work for `Image` objects, so `response.interact(egui::Sense::click())` is used to check for mouse clicks. 
However, after the recent update, left-clicking and right-clicking on an image are recognized about 1 in 100 times.

```rust
        let response = ui.add(image.show_loading_spinner(false));
        let response = response.interact(egui::Sense::click());
        if response.clicked() {
        }
        if response.secondary_clicked() {
        }
```

egui Version: v0.26.0 & master branch

### PR DESCRIPTION
**Pull request by rustbasic**
Closes #3989

@emilk 
Please review to see if there are any problems.

This Pull Request is Invalid `clip_rect`.
(For example, when the image is enlarged.)

self.ctx.layer_painter(self.layer_id).clip_rect() => Invalid
self.ctx.used_rect() => Invalid
self.ctx.available_rect() => Invalid
self.ctx.screen_rect() => Invalid
self.rect => Invalid

Is there a way to include `ui.clip_rect` in `Response` ?
or
Is there a way to not include `ui.clip_rect` in `Response` ?

I think ui.clip_rect needs to be included in Response.
ui.clip_rect To Response.clip_rect

### CODE REVIEW

**Comment by rustbasic** [comment]
Wait... Problem.

**Comment by rustbasic** [comment]
I think,
This PR is for reference by emilk in fixing bugs.

**Comment by emilk** [comment]
Before we switch away from `interact_with_hovered` I want to understand why it no longer works

**Comment by rustbasic** [comment]
The moment you click, `self.hovered` changes from `true` to `false`, and false is passed to self.ctx.interact_with_hovered().

**Comment by rustbasic** [comment]
Shouldn’t it be this way?

1. First, save all information with click_and_drag().
2. Then, information is removed according to the Sense settings.

**Comment by emilk** [comment]
Closed by #4013

**Pull request closed without merging**
