### PR TITLE
Improve documentation grammar and wording

### PR DESCRIPTION
**Pull request by Swarkin**
This PR aims to make the documentation comments easier to read and understand.

### CODE REVIEW

**Comment by Swarkin** [comment]
I don't know how to fix conflicts, sorry.

**Comment by Swarkin** [comment]
Fixed conflicts

**Comment by Swarkin** [comment]
Fixed conflicts

**Review by emilk — APPROVED** [review]

**Comment by emilk** [comment]
needs `cargo fmt`

**Comment by Swarkin** [comment]
Hi, cargo fmt does not change anything for me.

**Comment by lucasmerlin** [comment]
@Swarkin hmm, maybe you are on an older rust version?
Checking [the output](https://github.com/emilk/egui/actions/runs/10832498741/job/30187822132?pr=5052) of the  `Rust / Format + check + test` check will also tell you whats wrong: 

```diff
Diff in /home/runner/work/egui/egui/crates/egui/src/memory/mod.rs at line 172:
     #[cfg_attr(feature = "serde", serde(skip))]
     pub dark_style: std::sync::Arc<Style>,
 
-
     /// The default style for new [`Ui`](crate::Ui):s in light mode.
     #[cfg_attr(feature = "serde", serde(skip))]
     pub light_style: std::sync::Arc<Style>,
Diff in /home/runner/work/egui/egui/crates/egui/src/memory/mod.rs at line [18](https://github.com/emilk/egui/actions/runs/10832498741/job/30187822132?pr=5052#step:6:19)8:
     ///
     /// Default: [`crate::Theme::Dark`].
     pub fallback_theme: Theme,
-
 
     /// The current system theme, used to choose between
     /// dark and light style in case [`Self::theme_preference`] is [`ThemePreference::System`].
```

(you will need to remove the lines marked with `-`)

**Comment by Swarkin** [comment]
Done

**Pull request merged**
