### PR TITLE
egui-winit: Automatically detect and apply dark or light mode

### PR DESCRIPTION
**Pull request by emilk**
Closes https://github.com/emilk/egui/issues/1001

Uses the `dark-light` crate: https://crates.io/crates/dark-light

### CODE REVIEW

**Comment by emilk** [comment]
Oh, `dark-light` doesn't even _compile_ on Linux yet… I guess we'll wait with this until https://github.com/frewsxcv/rust-dark-light/pull/4 by @edfloreshz is merged and published

**Comment by emilk** [comment]
Blocked on:

* https://github.com/frewsxcv/rust-dark-light/issues/1

**Comment by parasyte** [comment]
Unfortunately, I think you'll also want https://github.com/frewsxcv/rust-dark-light/issues/3

**Comment by emilk** [comment]
We _want_ https://github.com/frewsxcv/rust-dark-light/issues/3 but it is not _needed_ in order to merge this

**Comment by parasyte** [comment]
I suppose polling for changes is acceptable in the meantime.

**Comment by Be-ing** [comment]
Is there an advantage to egui-winit doing this versus leaving applications to use dark-light if they want?

**Comment by emilk** [comment]
> Is there an advantage to egui-winit doing this versus leaving applications to use dark-light if they want?

One is to have a default: should egui be dark or light by default? Let's ask the system.
Second is convenience.

**Comment by collin-kemper** [comment]
dark-light currently breaks eframe on my machine. `dark_light::detect()` times out on my machine but takes 25 seconds to do so - meaning that starting an eframe app results in it freezing for the first 25 seconds. I've tried to disable the feature, but it doesn't seem like it is possible to disable it.

**Comment by collin-kemper** [comment]
#1437

**Comment by emilk** [comment]
Have you opened an issue at https://github.com/frewsxcv/rust-dark-light/issues @collin-kemper ?

**Pull request merged**
