### PR TITLE
Some performance improvements.

### LINKED ISSUE #4022: Immediate Viewport speed issue
Viewport speed issue

If you run `Immediate Viewport` while the program is at 60 frames (per second),
it will be at 50 frames.

If you have `two monitors` and the Viewport is on a different screen from the program,
the frame rate will be 30.

Is this a normal reaction?

egui version : ALL
OS : Windows 10

### LINKED ISSUE #4053: Unusable When Slowed Down
Unusable When Slowed Down

When the speed slows down, the FPS (frames per second) drops to 0-1, making it almost unusable.

How to slow down the speed :
Opening FontBook (egui_demo_app) after loading a font file with more than 40,000 fonts will slow down the program.

### PR DESCRIPTION
**Pull request by rustbasic**
Close #4022  

Some performance improvements.

### CODE REVIEW

**Comment by emilk** [comment]
Please elaborate on what is happening here

**Comment by rustbasic** [comment]
@emilk 

It's done up to this point.

There are no special bugs.
If you look at the source code, there is no special change from the original intention.

This is what everyone originally intended, and it eliminates commonly used bottlenecks and improves some subtle performance.
It may be difficult to notice performance improvements in simple programs, but performance has improved.

**Comment by rustbasic** [comment]
@emilk

Close #4022 

I think issue #4022 can be closed.
FPS is relatively improved at around 40-50.

Reducing FPS from 60 to 50 when creating a viewport is a separate issue.
I think it would be best to end here for now.

Not directly related to this, but influencing,
#4053 FontBook (bulk widget) issue still remains.

**Comment by rustbasic** [comment]
@emilk 

If #4054 is applied, all viewports will operate normally even if the program is minimized.

However, after applying #4026 yesterday, everything stopped working.

**Pull request closed without merging**
