### PR TITLE
translated part of the README

### PR DESCRIPTION
**Pull request by Re-Ch-Love**
Just an example, the translation work has not been completed.
related to #1647

### CODE REVIEW

**Comment by emilk** [comment]
This is very nice of you, but this is a also quite unusual. Not even https://github.com/rust-lang/rust has any translation of its `README.md`. It also puts me in a weird situation - if I change `README.md` the translation will be out-of-date with no way for me to update it.

**Comment by Re-Ch-Love** [comment]
> This is very nice of you, but this is a also quite unusual. Not even https://github.com/rust-lang/rust has any translation of its `README.md`. It also puts me in a weird situation - if I change `README.md` the translation will be out-of-date with no way for me to update it.

Maybe I can create a new repo to store the translation version, and try my best to ensure that it is synchronized with your repo (I can mark the version with git commit ID)
What's your opinion?

**Comment by emilk** [comment]
> Maybe I can create a new repo to store the translation version, and try my best to ensure that it is synchronized with your repo (I can mark the version with git commit ID) What's your opinion?

I think that's a good idea, and I can link to it from the egui README.md!

**Comment by Re-Ch-Love** [comment]
> > Maybe I can create a new repo to store the translation version, and try my best to ensure that it is synchronized with your repo (I can mark the version with git commit ID) What's your opinion?
> 
> I think that's a good idea, and I can link to it from the egui README.md!

I created a new repo, and you can link to [here](https://github.com/Re-Ch-Love/egui-doc-cn/).

You can mark the language with "简体中文", it means Simplified Chinese.

**Comment by emilk** [comment]
Added in https://github.com/emilk/egui/commit/e6cfa5028e2dd222ead311cf790d192ff401d0b9

**Pull request closed without merging**
