### PR TITLE
eframe web: ignore keyboard events unless canvas has focus

### PR DESCRIPTION
**Pull request by emilk**
* Fixes https://github.com/rerun-io/rerun/issues/6638
* Related? https://github.com/emilk/egui/issues/4563

This improves how an eframe canvas works inside of a larger web page, and how it works when there are multiple eframe apps in the same page.

`eframe` will set `tabindex="0"` on the canvas automatically, making it focusable.
It will also set `outline: none` on the CSS, so the focused canvas won't have an ugly outline.

## Breaking changes
You may wanna add this to your `index.html` to give the canvas focus on startup:
```js
document.getElementById("the_canvas_id").focus();
```

## Test setup
```sh
./scripts/build_demo_web.sh
./scripts/start_server.sh
open http://localhost:8888/multiple_apps.html
```
Then open the "Input Event History" and "Text Edit" windows

## Tested
* Chromium
	* [x] drag-and-drop of files
	* Test both when a `TextEdit` is focused and when it is not:
	  * [x] `Event::Key`
	  * [x] `Event::Text`
	  * [x] copy-cut-paste
	  * [x] Wheel scroll
	* [x] `Event::PointerGone`
	* [x] Mouse drag
	* [x] Mouse click
	* [x] Mouse right-click
	* [x] Defocus all eframe canvas, and then start typing text
* [x] Firefox (all of the above)
* [x] Desktop Safari (all of the above)
* [x] Mobile Safari

## Future work (pre-existing issues)
* https://github.com/emilk/egui/issues/4723
* https://github.com/emilk/egui/issues/4724
* https://github.com/emilk/egui/issues/4725
* https://github.com/emilk/egui/issues/4726

### CODE REVIEW

**Comment by jleibs** [comment]
This solves half of https://github.com/rerun-io/rerun/issues/6638

In a notebook context, Rerun no longer gets events when typing in notebook cells. However, it now fails to respect usage of any keyboard shortcuts at all.

Selecting a text-entry box works, but as soon as you leave a text-entry context it appears all events only get processed by the outer notebook environment.

**Comment by jprochazk** [comment]
Right click does not work in a notebook context (both classic and lab). For example, right click on a view in the blueprint panel should bring up its context menu, but instead it always opens the notebook's context menu

**Comment by emilk** [comment]
@jprochazk please see if the latest commit ([616fa2b](https://github.com/emilk/egui/pull/4718/commits/616fa2b371c92cb679da9736684c0194b5d16e0a)) fixes it

**Comment by jprochazk** [comment]
I can confirm it's fixed with that commit.

**Pull request merged**
