### PR TITLE
egui_winit+egui_glow on web

### LINKED ISSUE #1032: Try `egui_glow` with `egui-winit` on web
It would be great if we could get `egui-winit` to work on the web using `egui_glow` for rendering. If that worked, we could potentially make `eframe` just a thin wrapper around those two crates, with no need for `egui_web`.

Related: https://github.com/emilk/egui/pull/685 by @AlexApps99 and https://github.com/emilk/egui/pull/868 by @t18b219k. Also related: https://github.com/emilk/egui/issues/1022

### PR DESCRIPTION
**Pull request by t18b219k**
Closes #1032.
This PR Aims to reduce future maintenance cost for egui_glow ,egui_web and egui_winit. 
- [x]  eliminate crash on web.
- [x]  delete browser's context menu.
- [x]  type ascii chars.
- [x] open link.(webbrowser support it via web-sys.) 
- [ ]  IME support.
- [x]  port persistence on web for egui_winit.
- [ ]  clipboard
- [ ] multi touch

### CODE REVIEW

**Comment by t18b219k** [comment]
Implementing Clipboard operation for  egui-winit on web but No event handler fired.

**Comment by t18b219k** [comment]
In implementing tasks I found too many difference between native and web in winit .
therefore if we want to access glow then face many big challenge.
but persistence in web should move to epi .

**Comment by t18b219k** [comment]
winit on wasm very lack of feature and tried to add eventlistener to egui-winit to support IME I have to add many target_arch="wasm32" not(target_arch="wasm32") code

**Comment by emilk** [comment]
Thanks for your effort @t18b219k - sounds like `winit` isn't mature enough for this yet. Perhaps we should investigate https://github.com/tauri-apps/tao some day

**Pull request closed without merging**
