### PR TITLE
Add methods for custom number formatting in `DragValue` and `Slider`

### PR DESCRIPTION
**Pull request by Adanos020**
Closes <https://github.com/emilk/egui/issues/1221>.

As the title says, this PR adds a `custom_formatter` method for both `DragValue` and `Slider`. A custom formatter takes a `f64` for the numeric value and a `RangeInclusive<usize>` representing the decimal range.

The following code:

```rs
ui.add(egui::Slider::new(&mut self.age, 0..=120)
    .prefix("0x")
    .custom_formatter(|n, _| format!("{:X}", n as i64)));
ui.add(egui::DragValue::new(&mut self.age)
    .custom_formatter(|n, _| format!("{:03}", n as i64)));
```

produces the following result:

image

### CODE REVIEW

**Review by emilk — CHANGES_REQUESTED** [review]
Nice addition!

**Comment by Adanos020** [comment]
Applied suggested amendments and took care of the Github Actions' errors.

**Comment by emilk** [comment]
Thanks!

**Review by emilk — APPROVED** [review]

**Comment by Adanos020** [comment]
No worries, looking forward to the next release!

**Pull request merged**
