### PR TITLE
Fix `Panel` incorrect size

### PR DESCRIPTION
**Pull request by zhatuokun**
* Closes <https://github.com/emilk/egui/issues/4126>
* Closes <https://github.com/emilk/egui/issues/3006>

Previously, `SidePanel`/`TopBottomPanel`  didn't include `inner_margin` when setting the min width/height of `Frame`. As a result, when your `Panel` has `inner_margin`, its size doesn't work as expected.

Before

before

After

after

### CODE REVIEW

**Review by emilk — COMMENTED** [review]
Looks good, but please also update the docstrings of the `min_height, max_height, height_range etc` to explain they refer to the inner size, excluding the margins.

**Comment by zhatuokun** [comment]
> Looks good, but please also update the docstrings of the `min_height, max_height, height_range etc` to explain they refer to the inner size, excluding the margins.

Thanks! Previously, if you called `SidePanel::min_width` to set the minimum width to `150.0`, the previous algorithm would result in the SidePanel's actual minimum width being `150.0 + inner_margin.left + inner_margin.right`. Under the default margins, this would add an extra `16.0` in size, for a final SidePanel actual minimum width of `166.0`. Therefore, I subtract their inner_margin, meaning that when you use `min_width` to set the Panel's minimum width to `150.0`, the Panel's actual size is `150.0`, and the content inside is `150.0 - (inner_margin.left + inner_margin.right)`, which is consistent with the documentation description (`Minimum width of the panel.`). The same applies to other properties.

**Comment by emilk** [comment]
The problem with the existing documentation (and this is my mistake) is that "Minimum width of the panel" is not at all clear wether it is the outer size (size including margins) or the inner size (excluding the margins).

It seems the existing code was also confused, hence the bug. Bugs will keep cropping up unless we define explicitly wether or not the size includes the margins.

**Comment by zhatuokun** [comment]
That's true, for this aspect, perhaps we can refer to the design of CSS `box-sizing`, but that's another issue. For now, due to the two issues I mentioned above,  I suggest merging the changes after I add the document. I will start working on it soon.

**Review by emilk — APPROVED** [review]

**Comment by emilk** [comment]
Thanks!

**Pull request merged**
