### PR TITLE
Introduce egui::FullOutput, returned from Context::run

### PR DESCRIPTION
**Pull request by emilk**
This adds a new struct:

```
pub struct FullOutput {
    pub output: Output,
    pub needs_repaint: bool,
    pub textures_delta: epaint::textures::TexturesDelta,
    pub shapes: Vec<epaint::ClippedShape>,
}
```

The name is not great, nor the name of the nested `Output`, but structurally it works rather well.

Closes https://github.com/emilk/egui/issues/1281

### CODE REVIEW

**Comment by derivator** [comment]
I think I prefer the names I suggested: since this is a breaking change anyway, you might as well rename `Output`... `FullOutput` is a bit awkward.  
It's fine though, at least `handle_egui_output` does not return `TexturesDelta` anymore, I think that was the most confusing thing. :+1:

**Comment by emilk** [comment]
If we rename `Output` we should probably also rename `ctx.output()` which makes it even more of a breaking change :/

**Comment by derivator** [comment]
Ah, I see. I guess the use case there is e.g. for custom widgets to be able to open a URL or set the cursor? Seems like it's not something that most users would encounter often. egui itself only calls `output()` 15 times. Maybe deprecate it with a note to use the new name? That way calls of the form `ui.ctx().output()` would still work even though the name of the return type changed...

This makes me notice another issue though: custom widgets probably want to be able to set `needs_repaint`, right? Possibly even insert textures or shapes into the output? That seems like it has huge footgun potential though...

**Comment by emilk** [comment]
I renamed it `PlatformOutput` but kept the name `ctx.output()` for now. I don't want to spend too much time on this (I want to release egui 0.17.0!)

**Comment by derivator** [comment]
Looks good to me :+1: Thanks for all the work on egui, it really is a fantastic library :)

**Pull request merged**
