### PR TITLE
Fullscreen

### PR DESCRIPTION
**Pull request by jeremymeadows**
The default state can be set with the `NativeOptions` at compile time, and can be changed by using a callback to the UI context during runtime. The fullscreen state is written to the RON file so that the user-set state is restored on each launch.

I added a 'toggle fullscreen' button to the UI too, so that can be previewed.

Closes <https://github.com/emilk/egui/issues/662>.

### CODE REVIEW

**Comment by emilk** [comment]
Thanks for the PR!

`fullscreen` is not something that should be part of the `egui` crate, but instead should be part of the [`epi::Frame`](https://docs.rs/epi/0.14.0/epi/struct.Frame.html) API, just like `set_window_size` is!

**Comment by jeremymeadows** [comment]
Got it, sorry I didn’t see that second comment you made on the issue, but I'll see what I can do about moving that around :)

**Comment by jeremymeadows** [comment]
I got really busy with school stuff and work for several weeks, but finally winding down. I moved those changes around. It was a little tricky to deal with the AppOutput resetting itself every frame; that would undo whatever state was set in the previous frame. I pulled it out to give it slightly broader scope, and I didn't notice any problems it caused.

**Comment by emilk** [comment]
> It was a little tricky to deal with the AppOutput resetting itself every frame

Yeah, [it is in need of a refactor](https://github.com/emilk/egui/issues/673).

**Comment by emilk** [comment]
Any interest in this still?

**Comment by antouhou** [comment]
@emilk Yes! Is there any way I can help get this merged?

**Comment by emilk** [comment]
@antouhou Since a lot in this PR is outdated (a lot of epi/eframe refactor), I'm guessing your best bet it so create a new PR from scratch, perhaps with some inspiration taken from this one.

**Pull request closed without merging**
