### PR TITLE
Fix bug in custom window example

### PR DESCRIPTION
**Pull request by lorrenbiffin**
Addresses a bug in the drag behavior implementation for the `custom_window_frame` example.

---
#### Existing Behavior:
1. `Sense::drag()` enables "sensing" a mouse drag event on an interactive widget.
2. `title_bar_response.drag_started()` returns true when a drag event is "sensed" on `title_bar_rect`.
3. `frame.drag_window()` sets the `drag_window` property on the `AppOutput` struct.
4. `AppOutput` is passed to `winit` via `handle_app_output(..)` within eframe's epi integration.
5. `handle_app_output(..)` calls winit's `Window::drag_window()` method, which (finally) calls `winuser::PostMessageW(..)` to perform the window move behavior in-sync with the current mouse position.

#### Problem(s):
1. Winit and egui widget's internal drag behavior are at odds with each other when invoked at the same time.

#### Proposed Solution:
1. Allow the window drag handle (in this case, `title_bar_rect`) to sense clicks with `Sense::click()`.
    - Note: We don't need to (and probably shouldn't) sense dragging on the widget itself.
2. Detect when the mouse button is down on the title bar with `title_bar_response.is_pointer_button_down_on()`
3. Call `frame.drag_window()` and allow winit to do its job.
    - When the mouse button is released, `is_pointer_button_down_on()` no longer returns true, which allows `AppOutput` to tell winit that we're finished dragging, which ceases to call `PostMessageW(..)`, allowing mouse capture to return to egui.

---
Closes https://github.com/emilk/egui/issues/1518

### CODE REVIEW

**Comment by emilk** [comment]
Thanks for this, but I still don't understand what the bug is (`master` works on my Mac).

https://github.com/emilk/egui/issues/1518#issuecomment-1156314231 hints that it is maybe `dragged` that stops being `true` on non-mac/windows? If so, it would be great to get to the bottom of that problem.

**Comment by masc-it** [comment]
I am experiencing the same behaviour on Windows 10, only with the custom windows frame though. @lorrenbiffin your fix works, thank you 💯

**Comment by emilk** [comment]
Ok, let’s merge this then though I would love a deeper understanding of what goes wrong 🤔

**Comment by Ethanwolfie** [comment]
I also came across this problem on Window 10, with the latest commit [cd0f66b](https://github.com/emilk/egui/commit/cd0f66b9ae661be737ce57f26fb305cf124f6b73). After I swapped the code order as showed in the screeshot, the problem was gone.
codesnap

**Pull request merged**
