### PR TITLE
Add missing links to source code

### PR DESCRIPTION
**Pull request by c-git**
Closes <https://github.com/emilk/egui/issues/THE_RELEVANT_ISSUE>.

### CODE REVIEW

**Comment by c-git** [comment]
Please let me know if screenshot are needed. Not sure if it's worth the effort.

**Comment by c-git** [comment]
Tried to run the check script but it can't run as is. See error below.

```sh
$ ./scripts/check.sh 
+ cargo install --quiet cargo-cranky
+ cargo install --quiet typos-cli
error: failed to compile `typos-cli v1.17.0`, intermediate artifacts can be found at `/tmp/cargo-installOumziI`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

Caused by:
  package `varcon-core v4.0.4` cannot be built because it requires rustc 1.75 or newer, while the currently active rustc version is 1.72.0
  Try re-running cargo install with `--locked`
```

**Comment by ryo33** [comment]
@c-git I've temporary modified the rust-toolchain.toml to use the Rust version 1.75.0, and it works as a workaround of this error in my PR. I don't know should I open an issue or PR for this error.

**Comment by c-git** [comment]
That's fair, I guessed it was something like that but didn't have the time to check it.

**Comment by c-git** [comment]
I feel like since the PR would be small should be easy enough to do and get feedback on.

**Review by emilk — APPROVED** [review]

**Comment by emilk** [comment]
Thanks!

**Pull request merged**
