### PR TITLE
Update wgpu to 0.13

### PR DESCRIPTION
**Pull request by expenses**
**This should only be merged when a new wgpu release is made**

I'm using the git version of [naga](https://github.com/gfx-rs/naga/) and currently egui-wgpu panics during shader processing with that because it expects a different syntax for decorations, so I needed to make these changes to get it to work.

### CODE REVIEW

**Comment by emilk** [comment]
Is there a guide of different wgsl versions you could link to? It would be good to stick that in the `egui.wgsl` file as a guide to further changes!

**Comment by emilk** [comment]
Running this locally on my mac I get:

```
2022-05-27T08:08:43.837956Z  INFO wgpu_core::instance: Adapter Metal AdapterInfo { name: "Apple M1 Pro", vendor: 0, device: 0, device_type: DiscreteGpu, backend: Metal }    
2022-05-27T08:08:43.849075Z ERROR wgpu::backend::direct: Handling wgpu errors as fatal by default    
thread 'main' panicked at 'wgpu error: Validation Error

Caused by:
    In Device::create_shader_module
      note: label = `egui_shader`
    
Shader 'egui_shader' parsing error: expected field name or a closing curly bracket to signify the end of the struct, found '@'
  ┌─ wgsl:4:5
  │
4 │     @location(0) tex_coord: vec2<f32>,
  │     ^ expected field name or a closing curly bracket to signify the end of the struct


    expected field name or a closing curly bracket to signify the end of the struct, found '@'

', /Users/emilk/.cargo/registry/src/github.com-1ecc6299db9ec823/wgpu-0.12.0/src/backend/direct.rs:2273:5
```

**Comment by expenses** [comment]
@emilk These changes are in preparation for the next wgpu release which should bump naga.

**Comment by expenses** [comment]
I've updated this to the latest wgpu master.

https://github.com/gfx-rs/wgpu/pull/2808 and https://github.com/gfx-rs/wgpu/pull/2808 include some breaking changes so I've modified both the shader and cpu code as a result.

**Comment by expenses** [comment]
@emilk this should be mergeable now!

**Comment by expenses** [comment]
Utgh, I also need to update the syntax in the wgpu demo app: https://github.com/emilk/egui/blob/master/egui_demo_app/src/apps/custom3d_wgpu_shader.wgsl

Unfortunately, I don't know how to test this as the demo app seems pretty hardcoded to use glow at the moment, and I'm not invested enough to change this.

**Comment by expenses** [comment]
> Utgh, I also need to update the syntax in the wgpu demo app: https://github.com/emilk/egui/blob/master/egui_demo_app/src/apps/custom3d_wgpu_shader.wgsl

I've done that via checking it with the `naga` binary. Haven't tested the code though.

**Comment by emilk** [comment]
>  the demo app seems pretty hardcoded to use glow at the moment

Not at all! `(cd egui_demo_app && cargo r --features wgpu)`

**Review by emilk — APPROVED** [review]
Thank you!

**Pull request merged**
