### PR TITLE
Rough sdl2 backend and painter

### PR DESCRIPTION
**Pull request by tedsteen**
I needed egui to render and take input from SDL2, I did a rough implementation and would like to share it and this was the best way I could do that.

It's rough but might be a good starting point if someone would like to take it all the way.
The important stuff is [here](https://github.com/tedsteen/egui/tree/sdl2-backend/crates/egui_glow/src/sdl2)

I made two versions of the example [a basic one](https://github.com/emilk/egui/compare/master...tedsteen:egui:sdl2-backend?expand=1#diff-8c721fbcca9c28c46e9360561f3f9a478d9f6ff86b0bcc0a2ef1faf7fb558eb1) and one that fixes [this](https://stackoverflow.com/a/40693139) sdl2 resize "issue", it's [over here](https://github.com/emilk/egui/compare/master...tedsteen:egui:sdl2-backend?expand=1#diff-1342106d7a43a0de37c68427274272c264afa2420342f3a8689ed4d4a4eeb1df)

* Related to https://github.com/emilk/egui/issues/820

### CODE REVIEW

**Comment by tedsteen** [comment]
Sorry, that was a mis-click. Can't put it back to draft unfortunately..

**Comment by Mingun** [comment]
@tedsteen, convert to draft link located in **Reviewers** section on the right side:
изображение

**Comment by emilk** [comment]
See also:
* https://github.com/ArjunNair/egui_sdl2_gl
* https://github.com/ComLarsic/egui_sdl2_platform

**Comment by tedsteen** [comment]
> See also:
> 
> * https://github.com/ArjunNair/egui_sdl2_gl
> 
> * https://github.com/ComLarsic/egui_sdl2_platform

They where a great inspiration! But i wanted the glow + input through sdl2 and figured that a combo like that would be suitable for this repo, also considering the linked issue/discussion.

**Pull request closed without merging**
