### PR TITLE
Update accesskit to 0.17

### PR DESCRIPTION
**Pull request by lucasmerlin**
Updates accesskit and kittest. 

* [x] I have followed the instructions in the PR template

### CODE REVIEW

**Comment by lucasmerlin** [comment]
@mwcampbell the update was straightforward, but maybe you can review this in case I missed anything? 

Especially around the `set_default_action_verb`, I just removed those calls but am not 100% sure if I need to do anything else there.

**Comment by mwcampbell** [comment]
I see you dropped two calls to `set_default_action_verb`:

* `builder.set_default_action_verb(accesskit::DefaultActionVerb::Focus);`: This one is no longer necessary.
* `builder.set_default_action_verb(accesskit::DefaultActionVerb::Click);`: The if statement surrounding this needs to be re-added, but replace this statement with: `builder.add_action(accesskit::Action::Click);`.

The other problem is with the part where you use `builder.set_label`. If the role of the new node is `Role::Label`, you need to use `builder.set_value` instead.

**Comment by lucasmerlin** [comment]
@mwcampbell thank you for the review, I've updated the PR accordingly!

**Review by mwcampbell — APPROVED** [review]
LGTM now. I also did a quick test with a screen reader, and all looks right.

**Comment by mwcampbell** [comment]
Just checking: are you waiting on something else from me before merging? Thanks.

**Review by bircni — APPROVED** [review]
lgtm 👍

**Pull request merged**
