### PR TITLE
Fix drag_value.edit_string unexpected reset

### PR DESCRIPTION
**Pull request by tkkcc**
Make drag_value.edit_string None only during current focused widget update

Only two cases `edit_string` will be set to None (and reconstructed from `value`):

1. current widget gains focus.
2. current widget consumes up down key to change value.

Editing, Tabing and UpDown tested.

Close https://github.com/emilk/egui/issues/2418
Close https://github.com/emilk/egui/issues/2370

### CODE REVIEW

**Comment by tkkcc** [comment]
Still problematic. Editing DragValue then click another DragValue, the edit_string does not reset.

**Comment by tkkcc** [comment]
Fixed, add another reset on `request_focus`. Seems `gained_focus` is not satisfied this case.

**Comment by emilk** [comment]
@mwcampbell worked on this code recently - maybe you wanna take a look at this so it doesn't break AccessKit?

**Comment by mwcampbell** [comment]
I reviewed the code and tested it using only the keyboard and a screen reader, and it looks good to me.

**Comment by emilk** [comment]
Thanks for taking a look @mwcampbell! And thanks for the PR @tkkcc!

**Pull request merged**
