### PR TITLE
I want to add cjk support with default font

### PR DESCRIPTION
**Pull request by t18b219k**
I tested some cjk font below
- NotoSansCJKjp-Light rusttype says no glyph for glyph_id
- HanaMinA works but font size is big and extreamly difficult to recognize text
- HanaMinB works and same issue
- WenQuanYiMicroHei works and rusttype sample used this font

### CODE REVIEW

**Comment by t18b219k** [comment]
What license acceptable for this project?

**Comment by t18b219k** [comment]
Is Arphic font license acceptable?

**Comment by t18b219k** [comment]
I tried VL-Gothic it is good license but lack of hangul support and some hans

**Comment by emilk** [comment]
Hi, I guess there was some merge issue here?

**Pull request closed without merging**
