### PR TITLE
Red Green Color Blindness Debug Build Text

### PR DESCRIPTION
**Pull request by thomas992**
caption

### CODE REVIEW

**Comment by thomas992** [comment]
I did some math and figured out my color was off
caption
255*3=765 total color value to white/2=382.5 the medium between white and black
-255(from blue)= 127.5 remaining color / 2 = 67 for red and green

**Comment by thomas992** [comment]
caption

used the color dropper to adjust my math

**Comment by emilk** [comment]
The color red signifies warning, which is what I was going for. Sure, we can find a nicer tint of red that works better in dark and light mode, but I still think it can and should be red.

**Comment by thomas992** [comment]
One in twelve men are colorblind, more so in countries like Japan
[statistic](https://www.clintoneye.com/color-blindness.html#:~:text=There%20are%20an%20estimated%20300,are%20color%20blind%20(0.5%25).)
I think of it as a design philosophy if there is only one accent color it should be blue.

**Comment by emilk** [comment]
Being red-green color blind (Deutan) does not mean one cannot see red or green. I should know, I'm one. And using only one color where we could use several does not improve anything for anyone.

**Comment by thomas992** [comment]
the 580 line on the right side of the spectral formation might be better for text

**Comment by thomas992** [comment]
I just made it a hyperlink to Github. I did not really want to add a hyperlink but in retrospect it makes sense for people to pull up the GitHub from debug build.

**Comment by thomas992** [comment]
caption
I changed the hyperlink color on light theme as it was too bright to be clearly visible

**Comment by emilk** [comment]
If you want to be able to change the default warning color, perhaps add `warning_color: Color32` to [`Visuals`](https://docs.rs/egui/latest/egui/style/struct.Visuals.html) ?

**Pull request closed without merging**
