### PR TITLE
Fix typo: pupup -> popup

### PR DESCRIPTION
**Pull request by HackerFoo**
Fix typo: pupup -> popup

### CODE REVIEW

**Comment by coderedart** [comment]
I like pupup :dog2:

**Comment by emilk** [comment]
Pleas

**Comment by HackerFoo** [comment]
@emilk I suggest not doing this - it gives potential contributors a bad impression. There is also a burden to write small PRs.

I start with small PRs to decide whether it's worth putting effort into merging larger PRs, generally sorting my outstanding changes in increasing size and complexity.

I imagine others do the same to avoid wasting time, or at least to estimate how easy it is to get fixes upstreamed. Typo PRs are actually a good way to welcome new contributors.

For what it's worth, I wasted a few seconds wondering whether `pupup` was a typo, or if it meant something, did a find/replace, and checked that the code still worked. I wasn't looking for typos, I just encountered it and figured I'd save some others a bit of confusion. I made the change while making another functional change (#1091), but I think it is bad practice to bundle unrelated changes together.

**Comment by emilk** [comment]
@HackerFoo You make a good point, and I apologize. I agree that it is good to fix spelling and grammar (code readability is super important), and keeping changes separate is also a good idea. Though I would prefer for the change to be a separate commit in a bigger PR rather than a separate PR. Of course, this is my personal preference (and one that I have gone back and forth on over the years). I also haven't clearly stated my preference in the contributor guidelines, so that's on me.

There is also the context of people making commits with a single minor spelling fix in some unimportant file just to be able to be credited as contributors to a project, a behavior that just adds noise to the open source world.

Anyway, I changed the pupup -> poup in https://github.com/emilk/egui/commit/199bbef77bf59f9f5fa48346c715d827559e00cb#diff-eb4801118508476c267604aae155912ad2f8cae54490b4bc6d6ed9d0a3a38730

**Pull request closed without merging**
