### PR TITLE
TextEdit: Add visual clipping for singleline inputs when text is large.

### LINKED ISSUE #97: [Feature request] Fixed TextEdit width
https://user-images.githubusercontent.com/35241085/103775789-51141680-500d-11eb-9005-660db51083ab.mp4

I want to set the text input to a fixed width so it does not change the `SidePanel` width.

### PR DESCRIPTION
**Pull request by lucaspoffo**
Wow,

This PR adds visual clipping for singleline inputs. Currently the input grows with the text, now it will behave like the browser input, will keep the same size and show the text based on the cursor position.

Peek 2021-06-29 01-59

Fixes #97

### CODE REVIEW

**Comment by lucaspoffo** [comment]
@emilk There is some problems with the multiline input, but the singleline seems to work fine. I will try to fixes the problems another time, maybe tomorroy. But I want to see what you think about the solution I used

**Comment by lucaspoffo** [comment]
Managed to fix most the issues I was having:

- Multiline text input now behaves normally
- Text selection now considers the offset
- Simplified the logic 

Peek 2021-06-29 15-36

**Review by emilk — CHANGES_REQUESTED** [review]
Very nice, works as expected!

I left some suggestions

**Comment by lucaspoffo** [comment]
Thanks for the suggestions :+1: 
Already made the changes

**Review by emilk — APPROVED** [review]
Thank you!

**Pull request merged**
