### PR TITLE
Change local server IP addr to 127.0.0.1

### PR DESCRIPTION
**Pull request by 3119369616**
Change IP addr to 127.0.0.1

### CODE REVIEW

**Comment by singersbalm** [comment]
you can't reach the server from other devices if its 127.0.0.1. for example: `192.168.178.xxx` or `devicename.local`

**Comment by emilk** [comment]
Please explain why

**Comment by 3119369616** [comment]
> Please explain why
Because I can't run the local server if the ip addr is 0.0.0.0

OS of my computer is Win10.

**Comment by singersbalm** [comment]
I have used 0.0.0.0 in the past on windows

**Comment by emilk** [comment]
@3119369616 you should go to `127.0.0.1` in your browser, and the HTTP server bound on `0.0.0.0` will answer

**Pull request closed without merging**
